using System;
using System.ServiceModel;
using System.Threading.Tasks;

namespace WarehouseService
{
    public class Connection
    {
        private EmulatorServiceClient service;
        private string connection_string;
        public Connection(string connection)
        {
            connection_string = connection;
            service = new EmulatorServiceClient(connection_string);
        }

        //Check out the 'Connected Services>WarehouseService>Reference.cs' file to see autogenerated code. Read green text at the top.

        //runner
        public async Task RunExample()
        {
            //print response of GetInventoryAsync()
            var response = await service.GetInventoryAsync();
            Console.WriteLine(response);
        }
        
        public EmulatorServiceClient GetService()
        {
            return service;
        }

    }
}