using System;
using System.ServiceModel;
using System.Threading.Tasks;

namespace WarehouseService
{
    public class Connection
    {
        private EmulatorServiceClient service;
        public Connection()
        {
            service = new EmulatorServiceClient();
        }

        //Check out the 'Connected Services>WarehouseService>Reference.cs' file to see autogenerated code. Read green text at the top.

        //runner
        public async Task RunExample()
        {
            //print response of GetInventoryAsync()
            var response = await service.GetInventoryAsync();
            Console.WriteLine(response);
        }
        
    }
}